# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pyqtdesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(534, 11, 24, 24))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 420, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 360, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.Fractal_Canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.Fractal_Canvas.setGeometry(QtCore.QRect(140, 10, 631, 451))
        self.Fractal_Canvas.setObjectName("Fractal_Canvas")
        self.Fractal_Model_Selector = QtWidgets.QFontComboBox(self.centralwidget)
        self.Fractal_Model_Selector.setGeometry(QtCore.QRect(10, 100, 111, 22))
        self.Fractal_Model_Selector.setObjectName("Fractal_Model_Selector")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(10, 30, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(70, 30, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 140, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 200, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.xminSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xminSpinBox.setGeometry(QtCore.QRect(0, 160, 62, 22))
        self.xminSpinBox.setObjectName("xminSpinBox")
        self.xmaxSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xmaxSpinBox.setGeometry(QtCore.QRect(70, 160, 62, 22))
        self.xmaxSpinBox.setObjectName("xmaxSpinBox")
        self.yminSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.yminSpinBox.setGeometry(QtCore.QRect(0, 220, 62, 22))
        self.yminSpinBox.setObjectName("yminSpinBox")
        self.ymaxSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ymaxSpinBox.setGeometry(QtCore.QRect(70, 220, 62, 22))
        self.ymaxSpinBox.setObjectName("ymaxSpinBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 481, 751, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 121, 16))
        self.label_7.setObjectName("label_7")
        self.Number_of_Worker_text = QtWidgets.QLineEdit(self.centralwidget)
        self.Number_of_Worker_text.setGeometry(QtCore.QRect(10, 300, 113, 22))
        self.Number_of_Worker_text.setObjectName("Number_of_Worker_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DFR"))
        self.pushButton_2.setText(_translate("MainWindow", "Render"))
        self.pushButton.setText(_translate("MainWindow", "Send Params"))
        self.label.setText(_translate("MainWindow", "Xmin"))
        self.label_2.setText(_translate("MainWindow", "Xmax"))
        self.label_3.setText(_translate("MainWindow", "Ymin"))
        self.label_4.setText(_translate("MainWindow", "Ymax"))
        self.label_5.setText(_translate("MainWindow", "Image Size"))
        self.label_6.setText(_translate("MainWindow", "Model Name"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PRINT CLIENT CONNECTION MESSAGES HERE MIGUEL.</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Number of Workers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

